
spring:
  mvc:
    static-path-pattern: /**

  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.19.58.253)(PORT = 1604))(ADDRESS = (PROTOCOL = TCP)(HOST = 10.19.58.254)(PORT = 1604))(LOAD_BALANCE = yes)(FAILOVER = yes)(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = cjptdg)(FAILOVER_MODE=(TYPE = SELECT)(METHOD = BASIC)(RETIRES = 20)(DELAY = 15))))
    hikari: # springboot 2.0 整合了hikari ,据说这是目前性能最好的java数据库连接池
      username: cjpt2020
      password: Cjpt_2020X
  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update，要不然每次重启工程会删除表并新建
    show-sql: true
server:
  port: 8085